---
- name: Create archive from project folder
  become_user: "{{ remote_default_user }}"
  shell: "git archive master | gzip > {{ archive }}.tgz"
  args:
    chdir: "{{ temporary_dir | dirname  }}"
  delegate_to: localhost
  when: copy_strategy == 'archive'

- name: Move archive to playbook directory
  command: mv "{{ temporary_dir | dirname  }}/{{ archive }}.tgz"  "{{ temporary_dir }}/tmp"
  delegate_to: localhost
  when: copy_strategy == 'archive'
