---
- name: Import database from remote to host
  hosts: all
  gather_facts: no
  remote_user:  "{{ user }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_winrm_server_cert_validation: ignore
    database_dump_filename: dump
    database_dump_folder: "database/snapshots/{{ database_dump_filename }}.sql"
  tasks:

  - name: Include variables
    include_vars: "{{ playbooks_directory_path }}/variables/vars.yml"

  - name: Dump remote database
    shell: "php artisan snapshot:create {{ database_dump_filename }}"
    args:
      chdir: "{{ current_realease_path }}"

  - name: Copy file from remote to host
    fetch:
      src: "{{ current_realease_path }}/{{ database_dump_folder }}"
      dest: "{{ playbooks_directory_path | dirname }}/{{ database_dump_folder }}"
      flat: yes

  - name: Import remote database in host
    command: "php artisan snapshot:load {{ database_dump_filename }}"
    become: "{{ remote_default_user }}"
    args:
      chdir: "{{ playbooks_directory_path | dirname }}"
    delegate_to: localhost

  - name: Remove remote dump file
    shell: "php artisan snapshot:delete {{ database_dump_filename }}"
    args:
      chdir: "{{ current_realease_path }}"

  - name: Remove host dump file
    command: "php artisan snapshot:delete {{ database_dump_filename }}"
    become: "{{ remote_default_user }}"
    args:
      chdir: "{{ playbooks_directory_path | dirname }}"
    delegate_to: localhost

  # change all admins password to 12345678 php artisan administrable:snapshload
   # Change administrable guard passwords
    #   php artisan administrable:guard:create
     #  php artisan administrable:guard:update --field password --value 12345678 --id 5 --id 6 --all
     #  php artisan administrable:guard:update --field password --value 12345678 --all
      # change password
       #
        #

         #
