- name: Download source code
  become_user: "{{ remote_default_user }}"
  shell: "git clone {{ ansistrano_git_repo }} {{ archive }}"
  args:
    chdir: "{{ playbooks_directory_path }}/tmp"
  delegate_to: localhost
  when: copy_strategy == 'clone'

- name: Download source code
  delegate_to: localhost
  become_user: "{{ remote_default_user }}"
  archive:
    path: "{{ playbooks_directory_path }}/tmp/{{ archive }}/"
    dest: "{{ archive_path }}"
  when: copy_strategy == 'clone'
