---
- name: Generate app key
  shell: "php artisan key:generate --show > {{ ansistrano_shared_path }}/app_key"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
    creates: "{{ ansistrano_shared_path }}/app_key"

- name: Reading app key
  command: "cat {{ ansistrano_shared_path }}/app_key"
  register: app_key

