---
- name: Install supervisor
  apt:
    name: supervisor
    state: latest
  when: horizon == 'yes' or horizon == 'true'

- name: Make sure supervisor is running and started on boot
  service:
    name: supervisor
    state: started
    enabled: yes
  when: horizon == 'yes' or horizon == 'true'

- name: Make sure supervisor job is configured for Horizon
  template:
    src: "{{ playbooks_directory_path }}/templates/supervisor.conf.j2"
    dest: "/etc/supervisor/conf.d/{{ user }}-worker.conf"
  when: horizon == 'yes' or horizon == 'true'


- name: Link storage/public to public/storage
  file:
    src: "{{ ansistrano_shared_path }}/storage/app/public"
    path: "{{ ansistrano_release_path.stdout }}/public/storage"
    state: link

